Repository SeonghwiShin/opensw_android, pull requests merged in 2024-06, with the labels that each got.

#4 [Setting] gitignore 수정
  .gitignore
Labels: documentation

#5 [Setting] gitignore 수정
  .gitignore
Labels: documentation

#15 Feature/add fragment design [Feat] AddFragment 디자인 추가
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/java/com/opensw/sejongfood/MainFragment.kt
  app/src/main/res/layout/fragment_add.xml
Labels: enhancement

#17 [Bug] mapview 부모 스크롤뷰에 터치 중복되어서 생기는 문제 수정 Resolves:#16
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/res/layout/fragment_add.xml
Labels: bug

#19 [Setting] .editorconfig 추가
  .editorconfig
Labels: setting

#18 [Feat] 마커 로직 추가
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/res/drawable/icon_maker.png
  app/src/main/res/layout/fragment_add.xml
Labels: enhancement

#20 Feature/main bottomsheet [Feat] 메인 바텀시트 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/opensw/sejongfood/DetailBottomSheet.kt
  app/src/main/java/com/opensw/sejongfood/MainFragment.kt
  app/src/main/res/drawable/bottom_sheet_handle.xml
  app/src/main/res/layout/fragment_detail_bottom_sheet.xml
  app/src/main/res/layout/fragment_main.xml
Labels: enhancement

#21 Feature/add wish adapter [Feat] 찜하기 리사이클러뷰 추가
  app/src/main/java/com/opensw/sejongfood/PlaceData.kt
  app/src/main/java/com/opensw/sejongfood/WishAdapter.kt
  app/src/main/java/com/opensw/sejongfood/WishFragment.kt
  app/src/main/res/layout/fragment_wish.xml
  app/src/main/res/layout/item_holder.xml
Labels: enhancement

#22 [Feat] 마커 클릭이벤트 임시테스트 로직 추가
  app/src/main/java/com/opensw/sejongfood/MainFragment.kt
  app/src/main/res/layout/fragment_main.xml
Labels: enhancement

#23 [Feat] 다크모드 삭제, 상단바 색상 변경
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#24 Feature/add firebase [Feat] 파이어베이스 환경 추가
  app/build.gradle.kts
  app/google-services.json
  build.gradle.kts
Labels: enhancement

#25 Feature/firebase connect [Feat] 파이어베이스 연결
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/java/com/opensw/sejongfood/DetailBottomSheet.kt
  app/src/main/java/com/opensw/sejongfood/FirebaseHelper.kt
  app/src/main/java/com/opensw/sejongfood/MainActivity.kt
  app/src/main/java/com/opensw/sejongfood/MainFragment.kt
  app/src/main/java/com/opensw/sejongfood/PlaceData.kt
  app/src/main/java/com/opensw/sejongfood/WishAdapter.kt
  app/src/main/java/com/opensw/sejongfood/WishFragment.kt
Labels: enhancement

#26 Feature/review api [Feat] 리뷰작성 api 연결
  app/src/main/java/com/opensw/sejongfood/DetailBottomSheet.kt
  app/src/main/java/com/opensw/sejongfood/FirebaseHelper.kt
  app/src/main/java/com/opensw/sejongfood/MainFragment.kt
  app/src/main/java/com/opensw/sejongfood/ReviewAdapter.kt
  app/src/main/res/layout/dialog_add_review.xml
  app/src/main/res/layout/fragment_detail_bottom_sheet.xml
  app/src/main/res/layout/item_review_holder.xml
Labels: enhancement

#27 Feature/sharedpreference [Feat] SharedPreference 저장기능 추가
  app/build.gradle.kts
  app/src/main/java/com/opensw/sejongfood/DetailBottomSheet.kt
  app/src/main/java/com/opensw/sejongfood/SharedPreferenceUtil.kt
  app/src/main/java/com/opensw/sejongfood/WishAdapter.kt
  app/src/main/java/com/opensw/sejongfood/WishFragment.kt
  app/src/main/res/layout/fragment_detail_bottom_sheet.xml
Labels: enhancement

#28 [Feat] 주소 입력기능 추가
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/java/com/opensw/sejongfood/DetailBottomSheet.kt
  app/src/main/java/com/opensw/sejongfood/PlaceData.kt
  app/src/main/java/com/opensw/sejongfood/WishAdapter.kt
  app/src/main/res/layout/fragment_add.xml
Labels: enhancement

#29 Feature/design [Design] 디자인 리소스들 수정
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/java/com/opensw/sejongfood/MainFragment.kt
  app/src/main/java/com/opensw/sejongfood/ReviewAdapter.kt
  app/src/main/java/com/opensw/sejongfood/WishFragment.kt
  app/src/main/res/drawable/bottom_sheet_white_20.xml
  app/src/main/res/drawable/checkbox_wish.xml
  app/src/main/res/drawable/icon_maker1.png
  app/src/main/res/drawable/image_empty.png
  app/src/main/res/drawable/image_save.png
  app/src/main/res/drawable/image_trash.png
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/layout/fragment_detail_bottom_sheet.xml
  app/src/main/res/layout/fragment_wish.xml
  app/src/main/res/layout/item_review_holder.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#30 Feature/fix ux ux적으로 문제있는거 전부 수정
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/java/com/opensw/sejongfood/DetailBottomSheet.kt
  app/src/main/java/com/opensw/sejongfood/MainFragment.kt
  app/src/main/java/com/opensw/sejongfood/WishAdapter.kt
  app/src/main/res/layout/fragment_add.xml
Labels: bug, enhancement

#31 [Bug] 버그들 수정
  app/src/main/java/com/opensw/sejongfood/AddFragment.kt
  app/src/main/java/com/opensw/sejongfood/DetailBottomSheet.kt
  app/src/main/java/com/opensw/sejongfood/FirebaseHelper.kt
  app/src/main/java/com/opensw/sejongfood/WishAdapter.kt
  app/src/main/res/drawable/icon_maker1.png
Labels: bug
